## ARCHIVO EDITADO
## YODIE
import pandas as pd
data=pd.read_csv('dataTienda.csv',sep=',')
import sqlite3


conn=sqlite3.connect('tienda.db')
cursor_obj = conn.cursor()
cursor_obj.execute("DROP TABLE IF EXISTS USUARIOS")
table = """ CREATE TABLE USUARIOS (
            ID  INTEGER PRIMARY KEY AUTOINCREMENT,
            USUARIO VARCHAR(25),
            PASSWORD VARCHAR(255) NOT NULL,
            EMAIL VARCHAR(255) NOT NULL,
            FULLNAME VARCHAR(25) NOT NULL,
            SCORE INT,
            TIPOUSUARIO VARCHAR(25)
        ); """
cursor_obj.execute(table)
cursor_obj.execute("DROP TABLE IF EXISTS PRODUCTOS")
table = """ CREATE TABLE PRODUCTOS (
            NUMBER  INTEGER PRIMARY KEY AUTOINCREMENT,
            ID VARCHAR(255) NOT NULL,
            TIPO VARCHAR(255) NOT NULL,
            NOMBRE VARCHAR(25) NOT NULL, 
            PRECIO INT,
            CATEGORÍA VARCHAR(25) NOT NULL,
            STOCK INT,
         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ); """
cursor_obj.execute(table)
cursor_obj.execute("DROP TABLE IF EXISTS VENTA")
table=""" CREATE TABLE VENTA (
            ORDERID  INTEGER PRIMARY KEY AUTOINCREMENT,
            PRODUCTID INT, 
            NOMBRE
        TOTAL VARCHAR(25) NOT NULL
        ); """
cursor_obj.execute(table)
cursor_obj.execute("DROP TABLE IF EXISTS TASA")

table=""" CREATE TABLE TASA (
            ID  INTEGER PRIMARY KEY AUTOINCREMENT,
            MONEDA VARCHAR(25) NOT NULL, 
            VALOR INT
        ); """
cursor_obj.execute(table)

# comentamos las insercciones ya que solo sera parte de la creacion de tablas
""" insert =" INSERT INTO USUARIOS(USUARIO,PASSWORD,EMAIL,FULLNAME,SCORE,TIPOUSUARIO) VALUES('admin','admin','admin@datux.com','admin datux',0,'admin')"

conn.execute(insert)
insert =" INSERT INTO USUARIOS(USUARIO,PASSWORD,EMAIL,FULLNAME,SCORE,TIPOUSUARIO) VALUES('cliente','cliente','email','cliente',0,'cliente')"
conn.execute(insert)


print("Table is Ready")

print("ingrese valores")
TIPO=input('ingrese el nombre del producto')
NOMBRE=input('ingrese el NOMBRE:')
CATEGORÍAgria=input('ingrese el PRECIO:')
stock=int(input('ingrese el STCOKACTUAL:'))

insert="INSERT INTO PRODUCTOS(TIPO,NOMBRE,PRECIO,STCOKACTUAL) VALUES(?,?,?,?);"
data=(TIPO,NOMBRE,CATEGORÍAgria,stock)
conn.execute(insert,data)

insert =" INSERT INTO TASA(MONEDA,VALOR) VALUES('Dólar','3.9')"
conn.execute(insert)
insert =" INSERT INTO TASA(MONEDA,VALOR) VALUES('Euro','4.2')"
conn.execute(insert)


insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','SAMSUNG A50','100000','TEC','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 12','100000','TEC','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('20','PLAYGO','PLAYGO 100PCS','20000','TOY','50')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('24','BOARR GAMES','MONOPOLY','25000','TOY','50')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('21','PENCIL','FABER CASTELL','500','BOOKSHOP','1000')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('12','BASKETBALL','BASKETBALL BALL N10','15000','SPORT','600')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('213','BASKETBALL','NBA SHIRT','12000','SPORT','400')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('213','BASKETBALL','NBA SHIRT','12000','SPORT','400')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('14','BASKETBALL','BAND NBA','3000','SPORT','300')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('213','BASKETBALL','NBA SHIRT','12000','SPORT','400')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('16','CAM','HALLION CAM','8000','TEC','80')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('16','HANDSET','SONY AU 200','6500','TEC','90')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('16','KEYBOARD','HALLION KEY 200','12000','TEC','150')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('45','BOOK','NOTEBOOKS WHITE','850','BOOKSHOP','600')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('145','HAMERS','HAMMER WAVE','3500','TOOLS','80')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('89','TV','LG TV','120000','ELECTRONIC','120')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('169','TOYCAR','CAR CONTROL','15000','TOY','105')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('169','PUZZLE','DINO PUZZLE','4500','TOY','122')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('154','SMART BAND','SMART BAND 5','28900','TEC','106')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('168','washing machine','LG WASHINE 2','74500','ELECTRONIC','120')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('489','washing machine','SAMUNG WASHINE','98000','ELECTRONIC','59')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('365','Painting machine','CAT MACHINE','23900','TOOLS','93')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('366','toolbox','CAT TOOLBOX','25000','TOOLS','54')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('269','BOOK','Diary','4000','BOOKSHOP','62')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','78')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','89')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 13','120000','TEC','106')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('143','STAIRS','STAIRS DOUBLE','55000','TOOLS','60')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('169','FOOTBALL','SHIRT ADDIDAS','12000','SPORT','79')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('137','GYM','DUMBBELLS','25000','SPORT','67')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('189','BOOK','Diary 2','8000','BOOKSHOP','90')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('289','microwave','lg microwave','60000','ELECTRONIC','140')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('434','kitchen','mabe kitchen','40000','ELECTRONIC','82')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('375','toolbox','toolbox PRO','65000','TOOLS','84')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('315','DRONE','DJI DRONE','190000','ELECTRONIC','120')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('386','DOMOTICA','KIT DOMO','135000','ELECTRONIC','126')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('347','BOOK','THE RING COLLECTION','25000','BOOKSHOP','119')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('468','PUZZLE','SPACE PUZZZLE','15000','TOY','100')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('266','AIR','SAMSUNG AIR','100000','ELECTRONIC','114')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('276','TENNIS','RACKET','25000','SPORT','134')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('459','FOOTBALL','SET NIKE','','SPORT','76')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('265','CONSOLE','PS3','','TEC','113')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('250','BOOK','noteBoos white ','10000','BOOKSHOP','140')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('492','VIDEOGAMES','E FOOTBALL ','25000','TOY','67')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('386','BOOK',' The Godfather','25000','BOOKSHOP','65')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('377','LIGHT','LEDS ','4000','ELECTRONIC','94')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('459','DISPLAY','LED DISPLAY','25000','ELECTRONIC','89')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('477','FRIDGE','LG FRIDGE','150000','ELECTRONIC','91')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('265','kitchen','kitcken electro','1500','ELECTRONIC','111')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('440','led','set led','','ELECTRONIC','99')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('441','sound equip','lg max sound','','ELECTRONIC','97')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('337','auto card','android car','','ELECTRONIC','51')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('387','projector','epson projector','','ELECTRONIC','110')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('432','BOOK','HP ONE','40000','BOOKSHOP','118')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('251','BOOK','HP TWO','40000','BOOKSHOP','116')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('154','SMART BAND','SMART BAND 5','28900','TEC','74')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1','CELULAR','IPHONE 12','100000','TEC','94')"
conn.execute(insert)
insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES('1548','FOOTBALL','SHIRT NIKE','11000','SPORT','133')"
conn.execute(insert)


insert ="INSERT INTO PRODUCTOS(ID,TIPO,NOMBRE,PRECIO,CATEGORÍA,STOCK)VALUES(data.PRODUCT_ID.head(),data.NAME.head(),data.PRODUCT.head(),data.PRICE_UNIT.head(),data.CATEGORIA.head(),data.STOCK_ACUTAL.head())"
conn.execute(insert)


columns_select = ['PRODUCT_ID','NAME','PRODUCT','PRICE_UNIT','CATEGORIA', 'STOCK_ACUTAL']
data[columns_select].head()
"""



conn.commit()


